// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notification.proto

package notifications

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Notifications
type Notifications struct {
	Nots                 []*Notification `protobuf:"bytes,1,rep,name=nots,proto3" json:"nots,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Notifications) Reset()         { *m = Notifications{} }
func (m *Notifications) String() string { return proto.CompactTextString(m) }
func (*Notifications) ProtoMessage()    {}
func (*Notifications) Descriptor() ([]byte, []int) {
	return fileDescriptor_notification_baa484ff810b8202, []int{0}
}
func (m *Notifications) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notifications.Unmarshal(m, b)
}
func (m *Notifications) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notifications.Marshal(b, m, deterministic)
}
func (dst *Notifications) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notifications.Merge(dst, src)
}
func (m *Notifications) XXX_Size() int {
	return xxx_messageInfo_Notifications.Size(m)
}
func (m *Notifications) XXX_DiscardUnknown() {
	xxx_messageInfo_Notifications.DiscardUnknown(m)
}

var xxx_messageInfo_Notifications proto.InternalMessageInfo

func (m *Notifications) GetNots() []*Notification {
	if m != nil {
		return m.Nots
	}
	return nil
}

// Notification
type Notification struct {
	// notification id. Example:  “id” : “777”,
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// notification provider. Example:  “provider” : “Kyren”,
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	// notification service. Example:  “service” : “untiphishing”}
	Service              string   `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_notification_baa484ff810b8202, []int{1}
}
func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (dst *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(dst, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Notification) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *Notification) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func init() {
	proto.RegisterType((*Notifications)(nil), "notifgruber.Notifications")
	proto.RegisterType((*Notification)(nil), "notifgruber.Notification")
}

func init() { proto.RegisterFile("notification.proto", fileDescriptor_notification_baa484ff810b8202) }

var fileDescriptor_notification_baa484ff810b8202 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0xcb, 0x2f, 0xc9,
	0x4c, 0xcb, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x06, 0x8b, 0xa5, 0x17, 0x95, 0x26, 0xa5, 0x16, 0x29, 0xd9, 0x71, 0xf1, 0xfa, 0x21, 0x29, 0x29,
	0x16, 0xd2, 0xe5, 0x62, 0xc9, 0xcb, 0x2f, 0x29, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x92,
	0xd4, 0x43, 0x52, 0xac, 0x87, 0xac, 0x32, 0x08, 0xac, 0x4c, 0x29, 0x84, 0x8b, 0x07, 0x59, 0x54,
	0x88, 0x8f, 0x8b, 0x29, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x88, 0x29, 0x33, 0x45,
	0x48, 0x8a, 0x8b, 0xa3, 0xa0, 0x28, 0xbf, 0x2c, 0x33, 0x25, 0xb5, 0x48, 0x82, 0x09, 0x2c, 0x0a,
	0xe7, 0x0b, 0x49, 0x70, 0xb1, 0x17, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x4a, 0x30, 0x83, 0xa5,
	0x60, 0xdc, 0x24, 0x36, 0xb0, 0x4b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x26, 0x77, 0x66,
	0xd7, 0xbf, 0x00, 0x00, 0x00,
}
